version: v1.0
name: VPN Builder
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Build
    task:
      jobs:
        - name: Hello Android
          commands:
            - checkout &> /dev/null
            - git submodule update --init --recursive &> /dev/null
            - docker build . -t ci
            - docker run -it -e GH_PERSONAL_TOKEN=${GH_PERSONAL_TOKEN} -v $(pwd):/tmp/project ci
