language: minimal
os: linux
dist: bionic

before_script:
  # Update Docker coz travis has 18.06
  - sudo apt update &> /dev/null
  - sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y &> /dev/null
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - &> /dev/null
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" &> /dev/null
  - sudo apt install -y docker-ce docker-ce-cli containerd.io &> /dev/null
  - sudo systemctl start docker

script:
  - docker build . -t ci:latest
  - docker run -it -e GH_PERSONAL_TOKEN=${GH_PERSONAL_TOKEN} -v $(pwd):/tmp/project ci